[package]
name = "stdin-themefox-manager"
version = "0.1.0"
authors = ["Definitly not the author <lolsu@hash.fyi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"byteorder" = "*"
"serde_json" = "*"